import { StyleSheet } from "react-native";
import { useTheme } from "../../styles/theme";

export const useDriverStyles = () => {
  const { colors, shadows } = useTheme();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerCard: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.md,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: colors.text.primary,
    },
    headerSubtitle: {
      fontSize: 14,
      color: colors.text.secondary,
      marginTop: 4,
    },
    headerPill: {
      alignSelf: "flex-start",
      marginTop: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
    },
    headerPillText: {
      color: colors.text.inverse,
      fontSize: 12,
      fontWeight: "700",
    },
    scrollContent: {
      // padding: 20,
      paddingBottom: 40,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text.primary,
    },
    sectionSubtitle: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 4,
    },
    actionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginTop: 12,
      gap: 12,
    },
    actionButton: {
      width: "48%",
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 18,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    actionIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.secondary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    actionLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text.primary,
      textAlign: "center",
    },
    actionSubtext: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 4,
      textAlign: "center",
    },
    primaryButton: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 16,
    },
    primaryButtonText: {
      color: colors.text.inverse,
      fontSize: 14,
      fontWeight: "700",
    },
    mutedText: {
      fontSize: 12,
      color: colors.text.secondary,
    },
    avatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarText: {
      color: colors.text.inverse,
      fontSize: 20,
      fontWeight: "700",
    },
    badge: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: colors.secondary,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.text.primary,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 12,
    },
    topSpacing: {
      marginTop: 8,
    },
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    heroSurface: {
      padding: 20,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.md,
    },
    heroTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.text.primary,
    },
    heroSubtitle: {
      fontSize: 13,
      color: colors.text.secondary,
      marginTop: 4,
    },
    heroStatRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 16,
      gap: 10,
    },
    heroStatBox: {
      flex: 1,
      padding: 12,
      borderRadius: 12,
      backgroundColor: colors.secondary,
      alignItems: "center",
    },
    heroStatValue: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text.primary,
    },
    heroStatLabel: {
      fontSize: 11,
      color: colors.text.secondary,
      marginTop: 2,
    },
    headerSection: {
      borderRadius: 24,
      padding: 18,
      marginBottom: 16,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.md,
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    avatarContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    profileInfo: {
      flex: 1,
    },
    profileName: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text.inverse,
    },
    profileRoute: {
      fontSize: 12,
      color: colors.text.inverse,
      marginTop: 2,
      opacity: 0.9,
    },
    statusBadge: {
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
    },
    statusBadgeText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: "700",
    },
    contentContainer: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    progressSection: {
      marginBottom: 12,
    },
    progressLabel: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text.primary,
      marginBottom: 8,
    },
    progressTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    progressBarContainer: {
      flex: 1,
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.secondary,
      overflow: "hidden",
      marginRight: 12,
    },
    progressTrack: {
      flex: 1,
      backgroundColor: colors.secondary,
    },
    progressFill: {
      height: 8,
      backgroundColor: colors.primary,
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
    },
    progressPercent: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text.primary,
    },
    progressInfoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 8,
    },
    stopCounter: {
      fontSize: 12,
      color: colors.text.secondary,
    },
    etaText: {
      fontSize: 12,
      color: colors.text.secondary,
    },
    statsRow: {
      flexDirection: "row",
      marginTop: 16,
      gap: 10,
    },
    statBox: {
      flex: 1,
      backgroundColor: colors.secondary,
      borderRadius: 12,
      padding: 12,
      alignItems: "center",
    },
    statValue: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text.primary,
    },
    statLabel: {
      fontSize: 11,
      color: colors.text.secondary,
      marginTop: 2,
    },
    nextStopCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: colors.secondary,
      borderRadius: 16,
      padding: 14,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    nextStopLeft: {
      flex: 1,
    },
    nextStopLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.text.secondary,
      textTransform: "uppercase",
    },
    nextStopText: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text.primary,
      marginTop: 4,
    },
    nextStopSub: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 3,
    },
    nextStopCTA: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
    },
    quickActionsLabel: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text.primary,
      marginTop: 16,
      marginBottom: 10,
    },
    pillActionsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 10,
    },
    pillAction: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 999,
      gap: 6,
      minWidth: "48%",
      justifyContent: "center",
    },
    pillActionText: {
      color: colors.text.inverse,
      fontSize: 12,
      fontWeight: "700",
    },
    heroBadgeRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 12,
      gap: 12,
    },
    heroPill: {
      backgroundColor: "rgba(255,255,255,0.22)",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
    },
    heroPillText: {
      color: colors.text.inverse,
      fontSize: 12,
      fontWeight: "700",
    },
    heroHint: {
      flex: 1,
      color: colors.text.inverse,
      fontSize: 12,
      textAlign: "right",
      opacity: 0.9,
    },
    loadingCenter: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    loadingText: {
      marginTop: 16,
      color: colors.text.secondary,
      fontSize: 16,
    },
    errorText: {
      color: colors.error,
      fontSize: 16,
      textAlign: "center",
      marginBottom: 16,
    },
    retryBtn: {
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: colors.primary,
      borderRadius: 10,
    },
    retryText: {
      color: colors.text.inverse,
      fontWeight: "600",
    },
    content: {
      padding: 20,
      paddingBottom: 40,
    },
    settingsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 30,
    },
    settingButton: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      width: "48%",
      marginBottom: 16,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    settingIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.secondary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
    },
    settingIconText: {
      fontSize: 24,
    },
    settingTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text.primary,
      marginBottom: 4,
      textAlign: "center",
    },
    settingSubtitle: {
      fontSize: 12,
      color: colors.text.secondary,
      textAlign: "center",
      lineHeight: 16,
    },
    logoutBtn: {
      backgroundColor: colors.error,
      padding: 14,
      borderRadius: 8,
      alignItems: "center",
    },
    logoutText: {
      color: colors.text.inverse,
      fontWeight: "600",
    },
    // Schedule / Timeline
    scheduleCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    timelineRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      paddingVertical: 12,
    },
    timelineIndex: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    timelineIndexText: {
      color: colors.text.inverse,
      fontWeight: "700",
    },
    timelineBody: {
      flex: 1,
    },
    timelineTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text.primary,
    },
    timelineSubtitle: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 4,
    },
    viewFullRoute: {
      position: "absolute",
      right: 12,
      top: 12,
      color: colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    // Small stat cards
    smallStatRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 16,
      gap: 12,
    },
    smallStatCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    smallStatValue: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.text.primary,
    },
    smallStatLabel: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 6,
    },
    safetyCard: {
      marginTop: 16,
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    safetyText: {
      color: colors.text.primary,
      fontSize: 13,
    },
    // Top nav + greeting + weather
    topNav: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 10,
      backgroundColor: colors.background,
      width: "100%",
      alignSelf: "stretch",
      overflow: "hidden",
    },
    navTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: 18,
      fontWeight: "700",
      color: colors.text.primary,
    },
    navRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    bellContainer: {
      position: "relative",
      marginRight: 6,
    },
    bellBadge: {
      position: "absolute",
      right: -6,
      top: -6,
      backgroundColor: colors.error,
      width: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: "center",
      alignItems: "center",
    },
    bellBadgeText: {
      color: colors.text.inverse,
      fontSize: 10,
      fontWeight: "700",
    },
    avatarSmall: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    avatarImage: {
      width: 36,
      height: 36,
      borderRadius: 18,
    },
    avatarDot: {
      position: "absolute",
      right: -2,
      bottom: -2,
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#10B981",
      borderWidth: 2,
      borderColor: colors.surface,
    },
    greetingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    greetingText: {
      fontSize: 18,
      color: colors.text.primary,
      fontWeight: "700",
    },
    greetingSub: {
      fontSize: 13,
      color: colors.text.secondary,
      marginTop: 4,
    },
    weatherBox: {
      alignItems: "flex-end",
    },
    weatherTemp: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text.primary,
    },
    weatherCity: {
      fontSize: 12,
      color: colors.text.secondary,
    },
  });
};

export type DriverStyles = ReturnType<typeof useDriverStyles>;
