import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#BCE8B0",
  },
  gradient: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  loadingCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  loadingTitle: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
  },
  loadingSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: "#475569",
    textAlign: "center",
  },
  scrollContainer: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 28,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandWrap: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  logo: {
    width: 90,
    height: 90,
  },
  brandText: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: 0.4,
  },
  brandTextSecondary: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    marginLeft: 4,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  notificationWrap: {
    position: "relative",
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  badge: {
    position: "absolute",
    top: 2,
    right: 1,
    backgroundColor: "#F97316",
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#f3f6f7",
  },
  badgeText: { color: "#fff", fontSize: 10, fontWeight: "700" },
  avatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  greetingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  greeting: {
    fontSize: 28,
    fontWeight: "800",
    color: "#111827",
  },
  wave: {
    fontSize: 24,
    marginLeft: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#4B5563",
    marginTop: 4,
    marginBottom: 14,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
  },
  metricBox: {
    width: "48%",
    borderRadius: 18,
    padding: 12,
    minHeight: 118,
    marginBottom: 8,
  },
  metricIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  metricLabel: {
    color: "#374151",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  metricValue: {
    color: "#111827",
    fontSize: 25,
    fontWeight: "800",
    marginTop: 10,
  },
  metricChange: {
    fontSize: 11,
    fontWeight: "600",
    marginTop: 4,
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.38)",
    borderRadius: 18,
    padding: 10,
    marginTop: 12,
    marginBottom: 16,
  },
  quickBox: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  quickIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  quickTextWrap: {
    flex: 1,
  },
  quickLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#475569",
    letterSpacing: 0.5,
  },
  quickValue: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 4,
  },
  contentGrid: {
    flexDirection: "row",
  },
  leftPanel: {
    flex: 1,
  },
  rightPanel: {
    flex: 1.08,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  seeAll: {
    color: "#E11D48",
    fontSize: 11,
    fontWeight: "700",
  },
  alertList: {
    backgroundColor: "rgba(255,255,255,0.62)",
    borderRadius: 18,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginBottom: 18,
  },
  alertItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.12)",
  },
  alertIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  alertContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  alertTextWrap: {
    flex: 1,
    marginRight: 8,
  },
  alertText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  alertSubText: {
    fontSize: 11,
    color: "#6B7280",
    marginTop: 2,
  },
  supportBox: {
    backgroundColor: "rgba(255,255,255,0.62)",
    borderRadius: 18,
    padding: 12,
  },
  supportGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  supportCard: {
    width: "48%",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 72,
  },
  softRed: { backgroundColor: "#FEE2E2" },
  softBlue: { backgroundColor: "#DBEAFE" },
  softOrange: { backgroundColor: "#FDE68A" },
  softGreen: { backgroundColor: "#DCFCE7" },
  supportValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
  },
  supportLabel: {
    fontSize: 11,
    color: "#475569",
    marginTop: 3,
  },
  supportList: {
    marginTop: 6,
  },
  supportRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  supportDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#0EA5E9",
    marginRight: 8,
  },
  supportRowText: {
    flex: 1,
    fontSize: 12,
    color: "#374151",
  },
  statusPill: {
    fontSize: 10,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  statusHigh: { backgroundColor: "#FEE2E2", color: "#B91C1C" },
  statusMedium: { backgroundColor: "#FEF3C7", color: "#B45309" },
  statusLow: { backgroundColor: "#DCFCE7", color: "#166534" },
  primaryButton: {
    borderRadius: 14,
    backgroundColor: "#10B981",
    marginTop: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  routeList: {
    marginTop: 4,
  },
  tripCard: {
    backgroundColor: "rgba(255,255,255,0.66)",
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  tripMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#22C55E",
    marginRight: 8,
  },
  tripStatus: {
    fontSize: 11,
    fontWeight: "800",
    color: "#10B981",
  },
  tripRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 6,
  },
  tripTextWrap: {
    flex: 1,
  },
  tripRoute: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  tripDriver: {
    fontSize: 12,
    color: "#4B5563",
    marginTop: 4,
  },
  tripChildren: {
    fontSize: 12,
    color: "#4B5563",
    marginTop: 2,
  },
  mapMini: {
    width: 84,
    height: 70,
    borderRadius: 12,
    backgroundColor: "#E8F8EF",
    alignItems: "center",
    justifyContent: "center",
  },
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 12,
    backgroundColor: "#10B981",
    paddingVertical: 13,
    marginTop: 8,
    marginBottom: 18,
  },
  mapButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
  },
  chartCard: {
    backgroundColor: "rgba(255,255,255,0.66)",
    borderRadius: 18,
    padding: 14,
    marginBottom: 18,
  },
  range: {
    color: "#475569",
    fontSize: 11,
    fontWeight: "700",
  },
  chartLegend: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 14,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  legendText: {
    color: "#475569",
    fontSize: 11,
  },
  chartArea: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: 120,
    gap: 8,
    paddingTop: 10,
  },
  chartBar: {
    flex: 1,
    borderRadius: 8,
    minHeight: 16,
  },
  activityCard: {
    backgroundColor: "rgba(255,255,255,0.66)",
    borderRadius: 18,
    padding: 14,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  activityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  activityBody: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#111827",
  },
  activitySubtitle: {
    fontSize: 11,
    color: "#475569",
    marginTop: 2,
  },
  activityTime: {
    fontSize: 10,
    color: "#64748B",
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 18,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  navItemActive: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  navCenterButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#10B981",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  navText: {
    fontSize: 11,
    color: "#6B7280",
    marginTop: 2,
  },
  navTextActive: {
    fontSize: 11,
    color: "#0F172A",
    marginTop: 2,
    fontWeight: "700",
  },
});
