import { StyleSheet } from "react-native";

export const driverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F5FB",
  },
  headerSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatarContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#A78BFA",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFF",
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F2937",
  },
  profileRoute: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  statusBadge: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
  },
  scrollContent: {
    paddingBottom: 90,
  },
  card: {
    marginHorizontal: 20,
    borderRadius: 24,
    backgroundColor: "#FFF",
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  routeNameText: {
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "500",
    marginTop: 6,
  },
  cardBadge: {
    fontSize: 12,
    color: "#4A45D4",
    backgroundColor: "rgba(74,69,212,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    fontWeight: "700",
  },
  rideInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  rideText: {
    flex: 1,
    paddingRight: 12,
  },
  rideName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
  },
  rideTime: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 6,
  },
  busIconBox: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  routePoint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  routeLabel: {
    color: "#4B5563",
    fontSize: 14,
    fontWeight: "600",
  },
  routeDivider: {
    width: 1,
    height: 30,
    backgroundColor: "#E5E7EB",
    marginHorizontal: 12,
  },
  mapCard: {
    marginHorizontal: 20,
    backgroundColor: "#FFF",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  mapHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  mapTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  mapLink: {
    fontSize: 13,
    color: "#4A45D4",
    fontWeight: "700",
  },
  mapPreview: {
    height: 180,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  mapPinStart: {
    position: "absolute",
    left: 24,
    top: 40,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#4A45D4",
  },
  mapPinEnd: {
    position: "absolute",
    right: 24,
    bottom: 40,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#34C759",
  },
  mapLine: {
    width: "60%",
    height: 4,
    backgroundColor: "rgba(74,69,212,0.25)",
    borderRadius: 4,
  },
  rideHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  progressSection: {
    marginBottom: 18,
    paddingBottom: 18,
  },
  progressLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 10,
  },
  progressTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  progressInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stopCounter: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
  },
  etaText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#059669",
  },
  quickActionsLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 10,
    marginTop: 6,
  },
  progressPercent: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2563EB",
    minWidth: 40,
  },
  progressBarContainer: {
    flex: 1,
    position: "relative",
    height: 10,
    borderRadius: 8,
    backgroundColor: "#EFF6FF",
    overflow: "hidden",
  },
  progressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#EFF6FF",
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#2563EB",
    borderRadius: 8,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#F8FAFF",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 6,
  },
  nextStopCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#059669",
    borderRadius: 14,
    padding: 14,
    marginBottom: 18,
  },
  nextStopLeft: {
    flex: 1,
  },
  nextStopLabel: {
    fontSize: 12,
    color: "#D1FAE5",
    fontWeight: "600",
  },
  nextStopText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "800",
    marginTop: 3,
  },
  nextStopSub: {
    fontSize: 12,
    color: "#D1FAE5",
    marginTop: 6,
  },
  nextStopCTA: {
    marginLeft: 12,
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#047857",
    alignItems: "center",
    justifyContent: "center",
  },
  pillActionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  pillAction: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 12,
    borderRadius: 12,
  },
  pillActionText: {
    color: "#fff",
    fontWeight: "700",
    marginLeft: 8,
  },
  actionsGrid: {
    marginHorizontal: 20,
    marginBottom: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  actionButton: {
    width: "48%",
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  actionIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  actionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  announcementCard: {
    marginHorizontal: 20,
    backgroundColor: "#FFF",
    borderRadius: 24,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
  },
  announcementHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  announcementTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  announcementLink: {
    color: "#4A45D4",
    fontSize: 13,
    fontWeight: "700",
  },
  announcementText: {
    color: "#4B5563",
    fontSize: 14,
    lineHeight: 22,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  navText: {
    fontSize: 11,
    color: "#9CA3AF",
    marginTop: 4,
  },
  navTextActive: {
    fontSize: 11,
    color: "#4A45D4",
    marginTop: 4,
    fontWeight: "700",
  },
});
